pub use self::arch::{CODESET};
pub use self::arch::{D_T_FMT};
pub use self::arch::{D_FMT};
pub use self::arch::{T_FMT};
pub use self::arch::{T_FMT_AMPM};
pub use self::arch::{AM_STR};
pub use self::arch::{PM_STR};
pub use self::arch::{DAY_1};
pub use self::arch::{DAY_2};
pub use self::arch::{DAY_3};
pub use self::arch::{DAY_4};
pub use self::arch::{DAY_5};
pub use self::arch::{DAY_6};
pub use self::arch::{DAY_7};
pub use self::arch::{ABDAY_1};
pub use self::arch::{ABDAY_2};
pub use self::arch::{ABDAY_3};
pub use self::arch::{ABDAY_4};
pub use self::arch::{ABDAY_5};
pub use self::arch::{ABDAY_6};
pub use self::arch::{ABDAY_7};
pub use self::arch::{MON_1};
pub use self::arch::{MON_2};
pub use self::arch::{MON_3};
pub use self::arch::{MON_4};
pub use self::arch::{MON_5};
pub use self::arch::{MON_6};
pub use self::arch::{MON_7};
pub use self::arch::{MON_8};
pub use self::arch::{MON_9};
pub use self::arch::{MON_10};
pub use self::arch::{MON_11};
pub use self::arch::{MON_12};
pub use self::arch::{ABMON_1};
pub use self::arch::{ABMON_2};
pub use self::arch::{ABMON_3};
pub use self::arch::{ABMON_4};
pub use self::arch::{ABMON_5};
pub use self::arch::{ABMON_6};
pub use self::arch::{ABMON_7};
pub use self::arch::{ABMON_8};
pub use self::arch::{ABMON_9};
pub use self::arch::{ABMON_10};
pub use self::arch::{ABMON_11};
pub use self::arch::{ABMON_12};
pub use self::arch::{ERA};
pub use self::arch::{ERA_D_FMT};
pub use self::arch::{ERA_D_T_FMT};
pub use self::arch::{ERA_T_FMT};
pub use self::arch::{ALT_DIGITS};
pub use self::arch::{RADIXCHAR};
pub use self::arch::{THOUSEP};
pub use self::arch::{YESEXPR};
pub use self::arch::{NOEXPR};
pub use self::arch::{CRNCYSTR};

#[cfg(target_arch = "x86_64")]
#[path = "x86_64.rs"]
mod arch;

#[cfg(target_arch = "x86")]
#[path = "x86.rs"]
mod arch;

