pub struct stat {
    pub st_dev:        ::sys::types::dev_t,
    pub st_ino:        ::sys::types::ino_t,
    pub st_nlink:      ::sys::types::nlink_t,
    pub st_mode:       ::sys::types::mode_t,
    pub st_uid:        ::sys::types::uid_t,
    pub st_gid:        ::sys::types::gid_t,
    pub __pad0:        ::int_t,
    pub st_rdev:       ::sys::types::dev_t,
    pub st_size:       ::sys::types::off_t,
    pub st_blksize:    ::sys::types::blksize_t,
    pub st_blocks:     ::sys::types::blkcnt_t,
    pub st_atime:      ::sys::types::time_t,
    pub st_atime_nsec: ::long_t,
    pub st_mtime:      ::sys::types::time_t,
    pub st_mtime_nsec: ::long_t,
    pub st_ctime:      ::sys::types::time_t,
    pub st_ctime_nsec: ::long_t,
    pub __unused:      [::long_t,   ..3],
}
